apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: shortly
  labels:
    app: redis
    component: database
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  type: ClusterIP  # Internal access only 