apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: shortly
  labels:
    app: redis
    component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2  # AWS EBS General Purpose SSD 