apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-test
  namespace: shortly
  labels:
    app: load-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: load-test
  template:
    metadata:
      labels:
        app: load-test
    spec:
      containers:
      - name: load-generator
        image: busybox
        command: ["/bin/sh"]
        args:
        - -c
        - |
          # Download curl
          wget -O /tmp/curl https://github.com/moparisthebest/static-curl/releases/latest/download/curl-amd64
          chmod +x /tmp/curl
          
          echo "Starting load test..."
          
          # Generate continuous load
          while true; do
            # Backend health endpoint
            /tmp/curl -s http://backend.shortly.svc.cluster.local:8000/health >/dev/null 2>&1 &
            
            # Backend root endpoint  
            /tmp/curl -s http://backend.shortly.svc.cluster.local:8000/ >/dev/null 2>&1 &
            
            # Frontend health endpoint
            /tmp/curl -s http://frontend.shortly.svc.cluster.local/health >/dev/null 2>&1 &
            
            # Frontend root endpoint
            /tmp/curl -s http://frontend.shortly.svc.cluster.local/ >/dev/null 2>&1 &
            
            # CPU intensive operation
            dd if=/dev/zero of=/dev/null bs=1M count=10 >/dev/null 2>&1 &
            
            # Short sleep to prevent overwhelming
            sleep 0.1
          done
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "500m"
            memory: "128Mi" 