apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: shortly
  labels:
    app: shortly-backend
    component: api
type: Opaque
data:
  # Base64 encoded values - replace with actual secrets
  # To encode: echo -n "your-secret" | base64
  REDIS_PASSWORD: ""  # Empty for now, Redis without auth
  JWT_SECRET: "c29tZXNoLWp3dC1zZWNyZXQtaGVyZQ=="  # somesh-jwt-secret-here
  API_KEY: "c29tZXNoLWFwaS1rZXktaGVyZQ=="  # somesh-api-key-here 